# Generated by Django 4.0.2 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='Player ID')),
                ('birthYear', models.CharField(blank=True, max_length=15, null=True)),
                ('birthMonth', models.CharField(blank=True, max_length=15, null=True)),
                ('birthDay', models.CharField(blank=True, max_length=15, null=True)),
                ('birthCountry', models.CharField(max_length=50)),
                ('birthState', models.CharField(max_length=50)),
                ('birthCity', models.CharField(max_length=50)),
                ('deathYear', models.CharField(max_length=10)),
                ('deathMonth', models.CharField(max_length=10)),
                ('deathDay', models.CharField(max_length=10)),
                ('deathCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('deathState', models.CharField(blank=True, max_length=50, null=True)),
                ('deathCity', models.CharField(blank=True, max_length=50, null=True)),
                ('nameFirst', models.CharField(blank=True, max_length=50, null=True)),
                ('nameLast', models.CharField(blank=True, max_length=50, null=True)),
                ('nameGiven', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=15, null=True)),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('bats', models.CharField(max_length=2)),
                ('throws', models.CharField(max_length=2)),
                ('debut', models.CharField(blank=True, max_length=15, null=True)),
                ('finalGame', models.CharField(blank=True, max_length=15, null=True)),
                ('retroID', models.CharField(blank=True, max_length=15, null=True)),
                ('bbrefID', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
