# Generated by Django 4.0.2 on 2022-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Player ID')),
                ('birthYear', models.IntegerField()),
                ('birthMonth', models.IntegerField()),
                ('birthDay', models.IntegerField()),
                ('birthCountry', models.CharField(max_length=50)),
                ('birthState', models.CharField(max_length=50)),
                ('birthCity', models.CharField(max_length=50)),
                ('deathYear', models.IntegerField()),
                ('deathMonth', models.IntegerField()),
                ('deathDay', models.IntegerField()),
                ('deathCountry', models.CharField(max_length=50)),
                ('deathState', models.CharField(max_length=50)),
                ('deathCity', models.CharField(max_length=50)),
                ('nameFirst', models.CharField(max_length=50)),
                ('nameLast', models.CharField(max_length=50)),
                ('nameGiven', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bats', models.CharField(max_length=2)),
                ('throws', models.CharField(max_length=2)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('finalGame', models.DateTimeField(auto_now_add=True)),
                ('retroID', models.CharField(max_length=10)),
                ('bbrefID', models.CharField(max_length=10)),
            ],
        ),
    ]
